### ISSUE TITLE
Error working with laser driver: read_until: End of file

### ISSUE THREAD

**Issue by MONUNITH** [r3n33/lidar-lite-ros-scanner-driver#1]
Error working with laser driver: read_until: End of file

rosrun lidar_scanner_driver lidar_scanner_publisher _port:=/dev/ttyACM0 results in the above error

**Comment by r3n33** [comment]
The driver cannot communicate with your hardware at /dev/ttyACM0. You'll have to verify your hardware exists at that location and you have permission to access it.

**Comment by MONUNITH** [comment]
The hardware is there at /dev/ttyACM0 and gave full permission too still the same error is occurring

**Comment by MONUNITH** [comment]
The problem was with the connections I made, I didn't use pin no 8 it is working perfectly now.
